name = "cryptosignals"
compatibility_date = "2025-08-22"
compatibility_flags = ["python_workers"]
main = "./src/main.py"

[dev]
server = { workers_dev = true }

[vars]
ENVIRONMENT = "production"
ENV_VAR = "value"

